#!/usr/bin/env bash

pushd ~
    git clone git@github.com:cadedaniel/ray.git
    pushd ray
        git remote add upstream git@github.com:ray-project/ray.git
        git fetch upstream
        ./ci/env/install-bazel.sh
    popd
    git clone git@github.com:cadedaniel/cadelabs.git
    git clone git@github.com:anyscale/air-benchmarks.git

popd
