#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install zsh curl silversearcher-ag jq sysstat -y
#GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git clone git@github.com:cadedaniel/dotfiles.git
cd ~/dotfiles

rm ~/.gitconfig
rm ~/.vimrc
rm ~/.tmux.conf

./install-vim.sh
echo 'n' | ./install-zsh.sh
